"""
MCO Phase 3 — Perplexity Inversion Measurement Layer
======================================================
Measures the ratio PPL_G0(text) / PPL_Gk(text).

A healthy model (k=0) generates text that surprises itself about as much
as it surprises the reference model → ratio ≈ 1.0.

As collapse proceeds: Gk generates text it finds very predictable
(low PPL_Gk) while G0 finds those same outputs increasingly strange
(high PPL_G0) → ratio increases above 1.0.

Interface contract:
    measure(generated_samples, baseline_pack, **kwargs) -> dict[str, float]

Required kwargs:
    generating_model_path: str — path to the Gk checkpoint
    device: str — "cuda" or "cpu"

No imports from sibling modules. Completely standalone.

Self-test:
    python phase3_measurements/layers/perplexity_inversion.py
"""

import math
from typing import Any
import numpy as np


def _compute_ppl(model, tokenizer, texts: list[str],
                 device: str, max_length: int = 128) -> list[float]:
    """Compute per-sample perplexity for a list of texts."""
    import torch
    ppls = []
    model.eval()
    with torch.no_grad():
        for text in texts:
            enc = tokenizer(
                text,
                return_tensors="pt",
                truncation=True,
                max_length=max_length,
            ).to(device)
            if enc.input_ids.size(1) < 2:
                continue
            labels = enc.input_ids.clone()
            out = model(**enc, labels=labels)
            ppl = math.exp(out.loss.item())
            if math.isfinite(ppl):
                ppls.append(ppl)
    return ppls


def measure(
    generated_samples: list[str],
    baseline_pack: dict[str, Any],
    generating_model_path: str = None,
    device: str = "cpu",
    max_samples: int = 200,
    seed: int = 42,
    **kwargs,
) -> dict[str, float | int | None]:
    """
    Compute perplexity inversion ratio.

    PPL_inversion_ratio = mean(PPL_G0(text) / PPL_Gk(text))

    Args:
        generated_samples: texts generated by Gk
        baseline_pack: must contain g0_model_id or g0_checkpoint_path
        generating_model_path: path to Gk checkpoint
        device: "cuda" or "cpu"
        max_samples: max texts to evaluate (PPL is slow)
        seed: for reproducible subsampling

    Returns dict with keys:
        ppl_under_g0, ppl_under_gk, perplexity_inversion_ratio,
        std_ppl_inversion_ratio, n_valid_samples, ratio_deviation_from_1
    """
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    if generating_model_path is None:
        raise ValueError("generating_model_path is required for perplexity inversion")

    # Subsample deterministically
    rng = np.random.default_rng(seed)
    if len(generated_samples) > max_samples:
        idx = sorted(rng.choice(len(generated_samples), size=max_samples,
                                replace=False).tolist())
        samples = [generated_samples[i] for i in idx]
    else:
        samples = list(generated_samples)

    # Load tokenizer
    tok = AutoTokenizer.from_pretrained("distilgpt2")
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token

    # Load G0 (frozen reference — always distilgpt2 pretrained)
    g0_id = baseline_pack.get("g0_model_id", "distilgpt2")
    g0 = AutoModelForCausalLM.from_pretrained(g0_id).to(device)
    g0.eval()
    for p in g0.parameters():
        p.requires_grad = False

    # Load Gk
    gk = AutoModelForCausalLM.from_pretrained(generating_model_path).to(device)
    gk.eval()
    for p in gk.parameters():
        p.requires_grad = False

    ppls_g0 = _compute_ppl(g0, tok, samples, device)
    ppls_gk = _compute_ppl(gk, tok, samples, device)

    # Pair up valid results
    valid = [
        (p0, pk) for p0, pk in zip(ppls_g0, ppls_gk)
        if math.isfinite(p0) and math.isfinite(pk) and pk > 0
    ]

    if not valid:
        return {
            "error": "No valid PPL pairs computed",
            "n_valid_samples": 0,
            "perplexity_inversion_ratio": None,
        }

    p0s    = [v[0] for v in valid]
    pks    = [v[1] for v in valid]
    ratios = [p0 / pk for p0, pk in valid]

    mean_ratio = float(np.mean(ratios))
    std_ratio  = float(np.std(ratios))

    return {
        "ppl_under_g0":                 round(float(np.mean(p0s)), 4),
        "ppl_under_gk":                 round(float(np.mean(pks)), 4),
        "perplexity_inversion_ratio":   round(mean_ratio, 6),
        "std_ppl_inversion_ratio":      round(std_ratio, 6),
        "n_valid_samples":              len(valid),
        "ratio_deviation_from_1":       round(mean_ratio - 1.0, 6),
    }


# ── Self-test (synthetic — no real model needed) ───────────────────

if __name__ == "__main__":
    print("── Perplexity Inversion Self-Test ───────────────────────")
    passed = failed = 0

    def check(name, condition, detail=""):
        global passed, failed
        marker = "[PASS]" if condition else "[FAIL]"
        print(f"  {marker} {name}{' — ' + detail if detail else ''}")
        if condition:
            passed += 1
        else:
            failed += 1

    # Synthetic test: mock the PPL computation directly
    # Healthy: G0 PPL ≈ Gk PPL → ratio ≈ 1.0
    # Collapsed: Gk PPL << G0 PPL → ratio >> 1.0

    def _mock_result(ppl_g0_list, ppl_gk_list):
        valid = [(p0, pk) for p0, pk in zip(ppl_g0_list, ppl_gk_list)
                 if math.isfinite(p0) and math.isfinite(pk) and pk > 0]
        ratios = [p0/pk for p0, pk in valid]
        return {
            "ppl_under_g0": np.mean([v[0] for v in valid]),
            "ppl_under_gk": np.mean([v[1] for v in valid]),
            "perplexity_inversion_ratio": float(np.mean(ratios)),
            "n_valid_samples": len(valid),
        }

    rng = np.random.default_rng(42)
    # Healthy: both models score similarly
    g0_healthy = rng.normal(45, 5, 100).tolist()
    gk_healthy = rng.normal(44, 5, 100).tolist()
    r_h = _mock_result(g0_healthy, gk_healthy)

    # Collapsed: Gk is very confident (low PPL), G0 finds outputs strange (high PPL)
    g0_collapsed = rng.normal(70, 10, 100).tolist()
    gk_collapsed = rng.normal(20, 3, 100).tolist()
    r_c = _mock_result(g0_collapsed, gk_collapsed)

    check("Healthy ratio ≈ 1.0",
          0.8 <= r_h["perplexity_inversion_ratio"] <= 1.3,
          f"{r_h['perplexity_inversion_ratio']:.4f}")
    check("Collapsed ratio > Healthy ratio",
          r_c["perplexity_inversion_ratio"] > r_h["perplexity_inversion_ratio"],
          f"{r_c['perplexity_inversion_ratio']:.4f} > {r_h['perplexity_inversion_ratio']:.4f}")
    check("Collapsed ratio > 1.5",
          r_c["perplexity_inversion_ratio"] > 1.5,
          f"{r_c['perplexity_inversion_ratio']:.4f}")

    print(f"\n  {'✓ PERPLEXITY INVERSION SELF-TEST PASSED' if failed == 0 else '✗ PERPLEXITY INVERSION SELF-TEST FAILED'} "
          f"({passed}/{passed+failed})")
